config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  get '/edwardvanvliet', to: redirect('/search/brands/edward%20van%20vliet')

  scope module: 'spree' do
    get '/brands/:brand_name/*filter', to: "search#brands_redirect", as: 'brand_redirector'
    get '/collection', to: 'products#index', as: 'collection'
    post '/do_search', to: 'search#do_search'
    get '/country/set', to: 'country#set', as: 'set_country'
    get '/country/set_currency', to: 'country#set_currency', as: 'set_currency'
    get 'new_information_requests', to: 'information_requests#new', as: 'new_information_request'
    post 'create_information_requests', to: 'information_requests#create', as: 'create_information_request'
    get '/about', to: 'about_us#show', as: 'about'

    namespace :api, defaults: { format: 'json' } do
      resources :shipping_rates, only: [:index]
    end
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :information_requests
    resources :collection_images
  end
  resources :favorites, only: [] do
    collection do
      post :send_email
    end
  end
  get '/search', to: 'search#result', as: 'product_search'
  get '/search/*filters', to: 'search#result', as: 'product_search_filtered'
end

app/models/information_request.rb
class InformationRequest < ActiveRecord::Base
  # attr_accessible :address, :company, :email, :name, :question, :product_url
  
  validates :address, :company, :email, :name, :question, :product_url, presence: true
end

app/controllers/spree/admin/information_requests_controller.rb
module Spree
	module Admin
		class InformationRequestsController < Spree::Admin::BaseController
		  respond_to :html
		  
		  def index
				@information_reqs = InformationRequest.all
		  end
		  
		  def show
				@information_req = InformationRequest.find_by_id(params[:id])
		  end
		end
	end
end

app/controllers/spree/information_requests_controller.rb
module Spree
	class InformationRequestsController < BaseController
	  respond_to :html

	  def new
			@information_req = InformationRequest.new
	  end

	  def create
			@information_req = InformationRequest.new(information_request_params)
			if @information_req.save
				Spree::InformationRequestMailer.information_request_email(@information_req).deliver
				respond_with(@information_req) { |format| format.html { redirect_to @information_req.product_url, notice: "Thank you for request for information, we will respond to you shortly" } }
			else
				@information_req
				render :new
			end
	  end

		private
		def information_request_params
			params.require(:information_request).permit(:product_url,:email,:name, :company, :address, :question)
		end
	end
end

app/helpers/information_requests_helper.rb
module InformationRequestsHelper
end

app/views/spree/admin/information_requests/_information_request_menu.html.erb
<% if can? :admin, InformationRequest %>
    <ul class="nav nav-sidebar">
      <%= tab InformationRequest, url: spree.admin_information_requests_url, icon: 'file', label: InformationRequest.model_name.human(count: :many) %>
    </ul>
<% end %>

app/views/spree/admin/information_requests/index.html.erb
<h1><%= t(:listing_requests) %></h1>

<div id="requests" data-hook></div>

<table class="table" id="listing_requests">
  <tr data-hook="admin_products_index_headers">
    <th>Name</th>
    <th>Email</th>
    <th>Company</th>
<!--<th>Address</th>-->
    <th>Action</th>
  </tr>
<% @information_reqs.each do |req| %>
  <tr data-hook="information_requests">
    <td><%= req.name %></td>
    <td><%= req.email %></td>
    <td><%= req.company %></td>
<!--<td>< %= req.address %></td>-->
    <td><%= link_to 'Edit', admin_information_request_path(req), class: 'edit' %></td>
  </tr>
<% end %>
</table>

app/views/spree/admin/information_requests/show.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_product_link">
      <%= button_link_to t(:requests_list), admin_information_requests_path, {} %>
    </li>
  </ul>
  <br class="clear" />
</div>
<h1><%= t(:information_request) %></h1>


<table class="index" id="listing_requests">
  <tr data-hook="admin_products_index_headers">
    <th style="width:15%;">Name</th>
    <th style="width:20%;">Email</th>
    <th style="width:15%;">Company</th>
    <th style="width:20%;">Address</th>
    <th style="width:20%;">Question</th>
    <th style="width:10%;">Action</th>
  </tr>
  <tr data-hook="information_requests">
    <td><%= @information_req.name %></td>
    <td><a href="mailto:<%= @information_req.email %>"><%= @information_req.email %></a></td>
    <td><%= @information_req.company %></td>
    <td><%= @information_req.address %></td>
    <td><%= @information_req.question %></td>
    <td><a href="<%= @information_req.product_url %>">Product</a></td>
  </tr>
</table>