spree_image_cropper/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :images do
        member do
          get :crop
        end
      end
    end
  end
end

spree_image_cropper/app/models/spree/image_decorator.rb
Spree::Image.class_eval do
  require 'paperclip_processors/cropper'

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_update :reprocess_attachment, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def attachment_geometry(style = :original)
    @geometry ||= {}
    attachment_path = (attachment.options[:storage] == :s3) ? attachment.url(style) : attachment.path(style)
    @geometry[style] ||= Paperclip::Geometry.from_file(attachment_path)
  end

  private
  def reprocess_attachment
    attachment.assign(attachment)
    attachment.save
  end

end

spree_image_cropper/app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  attr_accessor :bulk_images
  before_save :process_bulk_images

  def process_bulk_images
    if bulk_images
      bulk_images.each do |img|
        self.images.create(attachment: img)
        # name = File.basename(img.original_filename, '.*')
        # self.images.new(:name => name, :alt => name )
      end
    end
  end
end

spree_image_cropper/app/controllers/spree/admin/images_controller_decorator.rb
Spree::Admin::ImagesController.class_eval do
  def crop
	 @product_dimension = Spree::Image.attachment_definitions[:attachment][:styles][:product].split("x").map(&:to_i)
  end
end

spree_image_cropper/app/views/spree/admin/images/crop.html.erb
<%= content_for :head do %>
<script type="text/javascript">
  $(function() {

      // Create variables (in this scope) to hold the API and image size
      var boundx, boundy;
      $('#cropbox').Jcrop({
        onChange: updatePreview,
        onSelect: updatePreview,
        aspectRatio: <%= @product_dimension[0] / @product_dimension[1] %>
      },function(){
        // Use the API to get the real image size
        var bounds = this.getBounds();
        boundx = bounds[0];
        boundy = bounds[1];
        // Store the API in the jcrop_api variable
        jcrop_api = this;
      });

      function updatePreview(c)
      {
        if (parseInt(c.w) > 0)
        {
          var rx = <%=@product_dimension[0]%> / c.w;
          var ry = <%=@product_dimension[1]%> / c.h;
          var ratio = <%= @image.attachment_geometry(:original).width %> / <%= @image.attachment_geometry(:crop).width %>;
          $('#crop_x').val(c.x * ratio);
          $('#crop_y').val(c.y * ratio);
          $('#crop_w').val(c.w * ratio);
          $('#crop_h').val(c.h * ratio);

          $('#crop_preview').css({
            width: Math.round(rx * boundx) + 'px',
            height: Math.round(ry * boundy) + 'px',
            marginLeft: '-' + Math.round(rx * c.x) + 'px',
            marginTop: '-' + Math.round(ry * c.y) + 'px'
          });
        }
      };
  });
</script>
<% end %>

<h2>Crop image</h2>
<p>Draw an area to mark the crop.</p>
<%= image_tag @image.attachment.url(:crop), id: "cropbox" %>

<h4>Preview</h4>
<div style="width: <%=@product_dimension[0]%>px; height: <%=@product_dimension[1]%>px; overflow: hidden;">
  <%= image_tag @image.attachment.url(:crop), id: "crop_preview" %>
</div>

<%= form_for [:admin, @product, @image], html: {multipart: true} do |form| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= form.hidden_field attribute, id: attribute %>
  <% end %>
  <%= form.hidden_field :viewable_id, value: @image.viewable_id %>

  <p class="form-buttons" data-hook="buttons">
    <%= button "Crop" %>
    <%= t(:or) %> <%= link_to t('actions.cancel'), admin_product_images_url(@product) %>
  </p>
<% end %>