spree_impressions/config/routes.rb
Spree::Core::Engine.routes.draw do

  resources :impressions, :only => [:index, :show]

  namespace :admin do
    resources :impressions do
      collection do
          post :update_positions
      end

      resources :images, :controller => "impressions/images" do
        member do
          get :crop
        end
        collection do
          post :update_positions
        end
      end
    end
  end
end

spree_impressions/app/models/spree/impression.rb
class Spree::Impression < ActiveRecord::Base
  has_many :images, as: :viewable, dependent: :destroy
  attr_accessor :bulk_images
  before_save :process_bulk_images

  has_many :impression_brands
  has_many :brands, :through => :impression_brands

  def name
    title
  end

  def process_bulk_images
    if bulk_images
      bulk_images.each do |img|
        self.images.new(:attachment => img)
      end
    end
  end
end

spree_impressions/app/models/spree/impression_brand.rb
class Spree::ImpressionBrand < ActiveRecord::Base
  belongs_to :brand, class_name: 'Spree::Taxon'
  belongs_to :impression
end

spree_impressions/app/controllers/spree/admin/impressions/images_controller.rb
module Spree
  module Admin
    module Impressions
      class ImagesController < ResourceController

        create.before :set_viewable
        update.before :set_viewable
        destroy.before :destroy_before

        def crop
          @product_dimension = Spree::Image.attachment_definitions[:attachment][:styles][:product].split("x").map(&:to_i)
        end

        private
        def load_resource
          @impression = Impression.find(params[:impression_id])

          if member_action?
            @object = @image = params[:id].nil? ? Spree::Image.new : Spree::Image.find(params[:id])
          else
            @collection = @images = @impression.images
          end
        end

        def location_after_save
          admin_impression_images_url(@impression)
        end

        def set_viewable
          @image.viewable_type = 'Spree::Impression'
          @image.viewable_id = @impression.id
        end

        def destroy_before
          @viewable = @image.viewable
        end

        def model_class
          Spree::Impression
        end

        def permitted_resource_params
          params[:image].present? ? params.require(:image).permit! : ActionController::Parameters.new
        end

      end
    end
  end
end

spree_impressions/app/controllers/spree/admin/impressions_controller.rb
module Spree
  module Admin
    class ImpressionsController < ResourceController

      before_action :set_brand_taxonomy_id

      def update
        if params[:impression][:brand_ids].present?
          params[:impression][:brand_ids] = params[:impression][:brand_ids].split(',')
        end
        super
      end

      protected

      def collection
        @collection = Impression.page(params[:page]).per(Spree::Config[:admin_products_per_page])
      end

      private

      def set_brand_taxonomy_id
        @brand_taxonomy_id = Spree::Taxonomy.find_by_name('Brands').try(:id)
      end
    end
  end
end

spree_impressions/app/controllers/spree/impressions_controller.rb
class Spree::ImpressionsController < Spree::BaseController

  def index
    @impressions = Spree::Impression.all
  end

  def show
    @impression = Spree::Impression.find(params[:id])
  end

  def accurate_title
    @impression ? "Impressions - #{@impression.name}" : "Impressions"
  end
end

spree_impressions/app/views/spree/admin/impressions/_form.html.erb
<fieldset>
  <div data-hook="admin_inside_background_form">
    <div class="row">
      <div class="col-md-6">
        <%= f.field_container :title, class: ['form-group'] do %>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
            <%= f.error_message_on :title %>
        <% end %>

        <%= f.field_container :sub_title, class: ['form-group'] do %>
            <%= f.label :sub_title %>
            <%= f.text_field :sub_title, class: 'form-control' %>
            <%= f.error_message_on :sub_title %>
        <% end %>

        <%= f.field_container :description, class: ['form-group'] do %>
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
            <%= f.error_message_on :description %>
        <% end %>

        <%= f.field_container :brands, class: ['form-group'] do %>
            <%= f.label :brand_ids, Spree.t(:brands) %>
            <%= f.hidden_field :brand_ids, value: @impression.brands.map(&:id).join(',') %>
        <% end %>

      </div>

      <div class="col-md-4">
        <fieldset>
          <legend><%= t(:multiple_image_upload) %></legend>
          <%= f.field_container :multiple_image_upload, class: ['form-group'] do %>
              <span>Upload multiple images here. You can edit them on the 'images' tab</span>
              <%= f.file_field :bulk_images, multiple: true %>
          <% end %>
        </fieldset>
      </div>
    </div>
  </div>
</fieldset>


<script type="text/javascript">
    'use strict';

    var set_taxon_select = function(){
        if ($('#impression_brand_ids').length > 0) {
            $('#impression_brand_ids').select2({
                placeholder: Spree.translations.taxon_placeholder,
                multiple: true,
                initSelection: function (element, callback) {
                    var url = Spree.url(Spree.routes.taxons_search, {
                        ids: element.val()
                    });
                    return $.getJSON(url, null, function (data) {
                        return callback(data['taxons']);
                    });
                },
                ajax: {
                    url: Spree.pathFor('api/taxons?taxonomy_id=<%= @brand_taxonomy_id %>'),
                    datatype: 'json',
                    data: function (term, page) {
                        return {
                            per_page: 50,
                            page: page,
                            without_children: true,
                            q: {
                                name_cont: term
                            }
                        };
                    },
                    results: function (data, page) {
                        var more = page < data.pages;
                        return {
                            results: data['taxons'],
                            more: more
                        };
                    }
                },
                formatResult: function (taxon) {
                    return taxon.pretty_name;
                },
                formatSelection: function (taxon) {
                    return taxon.pretty_name;
                }
            });
        }
    }

    $(document).ready(function () {
        set_taxon_select()
    });

</script>

spree_impressions/app/views/spree/admin/impressions/_sidemenu.html.erb
<% content_for :page_title do %>
    <%= link_to Spree.t(:impressions), admin_impressions_path %> /
    <%= @impression.title %>
<% end %>

<% content_for :sidebar do %>
    <ul class="nav nav-pills nav-stacked" data-hook="admin_impressions_tabs">
      <%= content_tag :li, :class => ('active' if current == 'Impression Details') do %>
          <%= link_to_with_icon 'edit', Spree.t(:details), edit_admin_impression_url(@impression) %>
      <% end if can?(:admin, Spree::Impression) %>
      <%= content_tag :li, :class => ('active' if current == 'Images') do %>
          <%= link_to_with_icon 'picture', "#{Spree.t(:images)} (#{@impression.images.count})", admin_impression_images_url(@impression) %>
      <% end if can?(:admin, Spree::Impression) %>
    </ul>
<% end %>

spree_impressions/app/views/spree/admin/impressions/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:edit_impression) %>
<% end %>

<%= render :partial => "sidemenu", :locals => { :current => 'Impression Details' } %>


<div data-hook="admin_impression_edit_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @impression } %>
</div>

<div data-hook="admin_impression_edit_form">
  <%= form_for [:admin, @impression], url: admin_impression_url(@impression), method: :put do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_impression_edit_form_button">
        <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_impressions_url } %>
      </div>
  <% end %>
</div>

spree_impressions/app/views/spree/admin/impressions/images/_form.html.erb
<div data-hook="admin_inside_background_form">
  <%= f.field_container :attachment, class: ['form-group'] do %>
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment %>
      <%= f.error_message_on :attachment %>
  <% end %>

  <%= f.field_container :alt, class: ['form-group'] do %>
      <%= f.label :alt, Spree.t(:alt_text) %>
      <%= f.text_area :alt, class: 'form-control' %>
      <%= f.error_message_on :alt %>
  <% end %>
</div>

spree_impressions/app/views/spree/admin/impressions/images/crop.html.erb
<%= content_for :head do %>

<script type="text/javascript">
  $(function() {

      // Create variables (in this scope) to hold the API and image size
      var boundx, boundy;
      $('#cropbox').Jcrop({
        onChange: updatePreview,
        onSelect: updatePreview,
        aspectRatio: <%= @product_dimension[0] / @product_dimension[1] %>
      },function(){
        // Use the API to get the real image size
        var bounds = this.getBounds();
        boundx = bounds[0];
        boundy = bounds[1];
        // Store the API in the jcrop_api variable
        jcrop_api = this;
      });

      function updatePreview(c)
      {
        if (parseInt(c.w) > 0)
        {
          var rx = <%=@product_dimension[0]%> / c.w;
          var ry = <%=@product_dimension[1]%> / c.h;
          var ratio = <%= @image.attachment_geometry(:original).width %> / <%= @image.attachment_geometry(:crop).width %>;
          $('#crop_x').val(c.x * ratio);
          $('#crop_y').val(c.y * ratio);
          $('#crop_w').val(c.w * ratio);
          $('#crop_h').val(c.h * ratio);

          $('#crop_preview').css({
            width: Math.round(rx * boundx) + 'px',
            height: Math.round(ry * boundy) + 'px',
            marginLeft: '-' + Math.round(rx * c.x) + 'px',
            marginTop: '-' + Math.round(ry * c.y) + 'px'
          });
        }
      };
  });
</script>
<% end %>

<h2>Crop image</h2>
<p>Draw an area to mark the crop.</p>
<%= image_tag @image.attachment.url(:crop), :id => "cropbox" %>

<h4>Preview</h4>
<div style="width: <%=@product_dimension[0]%>px; height: <%=@product_dimension[1]%>px; overflow: hidden;">
  <%= image_tag @image.attachment.url(:crop), :id => "crop_preview" %>
</div>

<%= form_for [:admin, @impression, @image] do |form| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= form.hidden_field attribute, :id => attribute %>
  <% end %>
  <%= form.hidden_field :viewable_id, :value => @image.viewable_id %>

  <p class="form-buttons" data-hook="buttons">
    <%= button "Crop" %>
    <%= t(:or) %> <%= link_to t('actions.cancel'), admin_impression_images_url(@impression) %>
  </p>
<% end %>

spree_impressions/app/views/spree/admin/impressions/images/edit.html.erb
<%= render :partial => 'spree/admin/impressions/sidemenu', :locals => {:current => 'Images'} %>

<% content_for :page_title do %>
    / <%= Spree.t(:edit_image) %>
<% end %>

<div data-hook="admin_impression_edit_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @impression } %>
</div>

<%= form_for [:admin, @impression, @image], :html => { :multipart => true } do |f| %>
    <%= f.field_container :thumbnail, class: ['form-group'] do %>
        <%= f.label :thumb, Spree.t('thumb')  %>
        <%= link_to image_tag(@image.attachment.url(:mini)), @image.attachment.url(:product), class: 'form-control' %>
    <% end %>
    <%= render :partial => 'form', :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_impression_images_url(@impression), :id => 'cancel_link' %>
  </p>
<% end %>

spree_impressions/app/views/spree/admin/impressions/images/index.html.erb
<%= render :partial => 'spree/admin/impressions/sidemenu', :locals => {:current => 'Images'} %>

<% content_for :page_title do %>
    / <%= Spree.t(:images) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_image), new_admin_impression_image_url(@impression), :id => 'new_image_link', :class => "btn-success", :icon => 'add' %>
<% end %>

<table class="table index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_impression_images_url(@impression) %>">
  <thead>
  <tr data-hook="images_header">
    <th><%= Spree.t(:thumb) %></th>
    <th><%= Spree.t(:alt_text) %></th>
    <th data-hook="admin_impression_images_header_actions" class="actions text-right"><%= Spree.t(:action) %></th>
  </tr>
  </thead>
  <tbody>
  <% @impression.images.each do |image| %>
      <tr id="<%= spree_dom_id image %>" data-hook="images_row">
        <td>
          <span class="handle"></span>
          <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
        </td>
        <td><%= image.alt %></td>
        <td class="actions text-right">
          <%= link_to_with_icon 'crop', t(:crop), crop_admin_impression_image_url(@impression, image) %>
          <%= link_to_with_icon 'edit', t(:edit), edit_admin_impression_image_url(@impression, image), :class => 'edit' %>
          &nbsp;
          <%= link_to_delete image, { :url => admin_impression_image_url(@impression, image) }%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div id="images" data-hook></div>

spree_impressions/app/views/spree/admin/impressions/images/new.html.erb
<%= render :partial => 'spree/admin/impressions/sidemenu', :locals => {:current => 'Images'} %>

<% content_for :page_title do %>
    / <%= Spree.t(:new_image) %>
<% end %>

<div data-hook="admin_impression_edit_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @impression } %>
</div>

<%= form_for [:admin, @impression, @image], :html => { :multipart => true } do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <p class="form-buttons" data-hook="buttons">
      <%= button t(:create) %>
      <%= t(:or) %> <%= link_to t(:cancel), admin_impression_images_url(@impression), :id => 'cancel_link' %>
    </p>
<% end %>

spree_impressions/app/views/spree/admin/impressions/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:impressions) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_impression), new_admin_impression_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_impression_link' %>
<% end %>

<table class="table" id="listing_impressions" data-hook>
  <thead>
  <tr data-hook="admin_impressions_index_headers">
    <th></th>
    <th>
      <%= Spree.t('thumb') %>
    </th>
    <th>
      <%= Spree.t('title') %>
    </th>
    <th>
      <%= Spree.t('sub_title') %>
    </th>
    <th data-hook="admin_impressions_index_header_actions" class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @impressions.each do |impression|%>
      <tr id="<%= spree_dom_id impression %>" data-hook="admin_impressions_index_rows">
        <td><span class="handle"></span></td>
        <td class='impression_thumb'>
          <% if impression.images.count > 0 %>
              <%= image_tag impression.images.first.attachment.url(:small) %>
          <% else %>
              No Images yet
          <% end %>
        </td>
        <td class='impression_title'><%= impression.title %></td>
        <td class='impression_sub_title'><%= impression.sub_title %></td>
        <td class='actions text-right' data-hook='admin_impression_index_row_actions'>
          <%= link_to_edit impression %>
          <%= link_to_delete impression %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @impressions %>

spree_impressions/app/views/spree/admin/impressions/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:new_impression) %>
<% end %>

<div data-hook="admin_impression_new_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @impression } %>
</div>

<div data-hook="admin_impression_new_form">
  <%= form_for [:admin, @impression], url: admin_impressions_url, method: :post do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_impression_new_form_buttons">
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      </div>
  <% end %>
</div>