spree_taxon_backgrounds/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :backgrounds do
      collection do
        post :update_positions
      end
    end
  end
end

spree_taxon_backgrounds/app/models/spree/background.rb
class Spree::Background < ActiveRecord::Base

  has_attached_file :image, :styles => {:thumb => "100x100>" },
      url: '/spree/backgrounds/:id/:style/:basename.:extension',
      path: ':rails_root/public/spree/backgrounds/:id/:style/:basename.:extension'
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :taxon, :class_name => "Spree::Taxon", :foreign_key => "taxon_id"
end

spree_taxon_backgrounds/app/controllers/spree/admin/backgrounds_controller.rb
module Spree
  module Admin
    class BackgroundsController < ResourceController
      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      protected

      def collection
        @collection = Background.page(params[:page]).per(Spree::Config[:admin_products_per_page])
      end
    end
  end
end

spree_taxon_backgrounds/app/views/spree/admin/backgrounds/_form.html.erb
<div data-hook="admin_inside_background_form">
  <%= f.field_container :image, class: ['form-group'] do %>
      <%= f.label :image, Spree.t(:image) %>
      <%= f.file_field :image %>
  <% end %>

  <%= f.field_container :taxon, class: ['form-group'] do %>
      <%= f.label :taxon_id, t(:taxon) %><br />
      <%= f.collection_select(:taxon_id, Spree::Taxon.all, :id, :name, { :include_blank => true }, { 'style' => 'width:200px' }) %>
  <% end %>
</div>

spree_taxon_backgrounds/app/views/spree/admin/backgrounds/edit.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:edit_background) %>
<% end %>

<div data-hook="admin_background_edit_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @background } %>
</div>

<div data-hook="admin_background_edit_form">
  <%= form_for [:admin, @background], url: admin_background_url(@background), method: :put do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_background_edit_form_button">
        <%= render :partial => 'spree/admin/shared/edit_resource_links', :locals => { :collection_url => admin_backgrounds_url } %>
      </div>
  <% end %>
</div>

spree_taxon_backgrounds/app/views/spree/admin/backgrounds/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:backgrounds) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_background), new_admin_background_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_background_link' %>
<% end %>

<table class="table" id="listing_backgrounds" data-hook>
  <thead>
  <tr data-hook="admin_backgrounds_index_headers">
    <th>
      <%= Spree.t('thumb') %>
    </th>
    <th>
      <%= Spree.t('taxon') %>
    </th>
    <th data-hook="admin_backgrounds_index_header_actions" class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @backgrounds.each do |background|%>
      <tr id="<%= spree_dom_id background %>" data-hook="admin_backgrounds_index_rows">
        <td class='background_thumb'><%= image_tag background.image(:thumb) %></td>
        <td class='background_taxon'>
          <% if background.taxon %>
              <%= background.taxon.name %>
          <% end %>
        </td>
        <td data-hook="admin_backgrounds_index_row_actions" class="actions actions-2 text-right">
          <%= link_to_edit background, :no_text => true %>
          <%= link_to_delete background, :no_text => true %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @backgrounds %>

spree_taxon_backgrounds/app/views/spree/admin/backgrounds/new.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:new_background) %>
<% end %>

<div data-hook="admin_background_new_form_header">
  <%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @background } %>
</div>

<div data-hook="admin_background_new_form">
  <%= form_for [:admin, @background], url: admin_backgrounds_url, method: :post do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div data-hook="admin_user_new_form_buttons">
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      </div>
  <% end %>
</div>